Add Advanced Load Balancing Methods to Router
nginxinc/nginx-plus-router pull request #12
Opened 2018-11-27 20:37 UTC by SirNexus

Add advanced load balancing methods to NGINX and NGINX Plus Routers and update respective documentation. Methods include:

NGINX Router:
HTTP/TCP:

* random
* random_two_least_conn

NGINX Router with NGINX Plus
HTTP:

* random
* random two least_conn
* random two least_time=header
* random two least_time=last_byte
* least_time header
* least_time last_byte
* least_time header inflight
* least_time last_byte inflight
TCP:

* random
* random two least_conn
* random two least_time=connect
* random two least_time=first_byte
* random two least_time=last_byte
* least_time connect
* least_time first_byte
* least_time last_byte
* least_time connect inflight
* least_time first_byte inflight
* least_time last_byte inflight

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-openshift-router/blob/master/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

2018-11-28 13:54 UTC, pleshakov requested changes
Looks good. But a small change is needed

2018-11-28 13:54 UTC, pleshakov commented on docs/configuration.md
> +## Fine-Tuning Load Balancing Methods with NGINX Plus
this section is inserted in the middle of `TCP/UDP Load Balancing Extension`. Please move it

2018-11-28 17:53 UTC, Dean-Coakley approved these changes

2018-11-29 16:30 UTC, pleshakov approved these changes

2018-12-03 01:35 UTC, merged