Added instructions for firewalld
nginxinc/nginx-plus-router pull request #14
Opened 2019-02-16 22:00 UTC by CountPickering

### Proposed changes
Added firewalld instructions on the installation pages.  Also specified "infra nodes" in plural tense for the event multiple routers are run.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/nginx-openshift-router/blob/master/CONTRIBUTING.md) guide
- [x] I have proven my fix is effective or that my feature works
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the master branch and pulling from my branch on my own fork

2019-02-18 11:31 UTC, pleshakov requested changes
@CountPickering thanks for the PR!

I've added a few small suggestions, could you possibly implement them?

Additionally, because port 1936 is not used for regular traffic like ports 80 and 443, but rather the admin traffic, is it possible to extend the `firewall-cmd` instruction to include the source range, similarly to the existing iptables command.

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-oss-router-install.md
> +1. By default, the NGINX stub status page is available via port 1936 on each of the infra nodes where the Router is running (you can change this port with the `STATS_PORT` env variable). To access th
```suggestion
1. By default, the NGINX stub status page is available via port 1936 on each of the infra nodes where the Router is running (you can change this port with the `STATS_PORT` env variable). To access the page outside of the nodes, open the port in the firewall using **iptables** or **firewall-cmd** on those nodes:
```

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-oss-router-install.md
> +    Firewalld
```suggestion
    firewall-cmd:
```

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-plus-router-install.md
> +1. By default, the NGINX stub status page is available via port 1936 on each of the infra nodes where the Router is running (you can change this port with the `STATS_PORT` env variable). To access th
```suggestion
1. By default, the NGINX stub status page is available via port 1936 on each of the infra nodes where the Router is running (you can change this port with the `STATS_PORT` env variable). To access the page outside of the nodes, open the port in the firewall using **iptables** or **firewall-cmd** on those nodes:
```

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-plus-router-install.md
> +    Firewalld
```suggestion
    firewall-cmd:
```

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-plus-router-install.md
> +    IPtables
```suggestion
    iptables:
```

2019-02-18 11:31 UTC, pleshakov commented on docs/nginx-oss-router-install.md
> +    IPtables
```suggestion
    iptables:
```

2019-02-18 14:22 UTC, CountPickering commented
Your suggestions are on target and have been implemented.

2019-02-18 17:12 UTC, Rulox approved these changes

2019-02-18 18:41 UTC, pleshakov commented
@CountPickering Thanks for implementing those suggestions!

> Additionally, because port 1936 is not used for regular traffic like ports 80 and 443, but rather the admin traffic, is it possible to extend the `firewall-cmd` instruction to include the source range, similarly to the existing iptables command.

regarding the comment above, can this be addressed?

if there are no simple firewall-cmd commands for this case, then it makes sense to put a note right after the command. Something like below:

**Note**: For simplicity, the firewall-cmd commands listed above do not configure the source IP range of the allowed traffic. It is recommended that you configure the source IP range to protect the [stub status page|dashboard] similarly to the iptables command.

2019-02-18 22:28 UTC, CountPickering commented
I would add the note as you suggested.  With firewalld you can define a range but it requires the setup of a zone.  The OpenShift 3.11 installer uses the public zone by default.

2019-02-19 10:38 UTC, pleshakov commented
@CountPickering that sounds good! thx

2019-03-08 17:44 UTC, pleshakov approved these changes
@CountPickering Thanks!
Could you possibly squash your commits into a single one? Once that is done, we'll merge the PR.

2019-05-07 11:23 UTC, magicalyak commented
Just a note, this could be further expanded by demonstrating the command
```
$ sudo firewall-cmd --permanent --zone=public \ 
 --add-rich-rule='rule family="ipv4" \
 source address="1.2.3.4/32" \ 
 port protocol="tcp" \
 port="1936" accept'
$ sudo firewall-cmd --reload
```

2025-12-26 18:33 UTC, closed without merging